[package]
name = "moho-types"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh.workspace = true
hex.workspace = true
sha2.workspace = true
strata-predicate.workspace = true
zkaleido.workspace = true
